// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dejiesrhzlxzrmhdjine.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlamllc3Joemx4enJtaGRqaW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTY2NDcsImV4cCI6MjA3MjMzMjY0N30.411VNtetoQtJq0om6TgM4L4ITSqi0i39gi2_Lgtpqt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);